version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./users.db:/app/users.db
      - ./media:/app/media
      - ./config.py:/app/config.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bot-network

  nginx:
    image: nginx:alpine
    container_name: telegram-bot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./admin/build:/usr/share/nginx/html
      - ./media:/usr/share/nginx/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - telegram-bot
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  media:
    driver: local 